#!/usr/bin/env bash
# Installing nginx on your web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#Testing the nginx configurations
sudo nginx -t

sudo service nginx reload
