#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 80.
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart

