#!/usr/bin/env bash
# A bash script that displays numbers from 1 to 100.

# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

y=1
while [ $y -ne 101 ]
do
    if [ $((y % 15)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((y % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((y % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
	echo $y
    fi
    ((y++))
done

