#!/usr/bin/env bash
# A Bash script that listens on port 98 on localhost.
# Connecting to localhost on port 98 using telnet
# and typing some text.
# Receiving the text on the other side.
nc -l localhost 98
